### PR TITLE
Feature/add refresh access token method to api client

### PR DESCRIPTION
**Pull request by 4c0n**
As discussed with @LarryKlugerDS in issue: https://github.com/docusign/docusign-php-client/issues/87

Hereby my PR that adds a method to the `ApiClient` that is to be used to refresh the OAuth2 access tokens. As you can see, it's only a small change :)

### CODE REVIEW

**Comment by 4c0n** [comment]
@larrykluger @LarryKlugerDS @MattKingDS @TonyMannDS @jwimberley-ds Is it possible for any of you to review this PR? It shouldn't take up too much of your time.
Thanks in advance for your time and effort!

**Comment by 4c0n** [comment]
@larrykluger @LarryKlugerDS @MattKingDS @TonyMannDS @jwimberley-ds Friendly reminder :)

**Comment by 4c0n** [comment]
@larrykluger @LarryKlugerDS @MattKingDS @TonyMannDS @jwimberley-ds Another 2 weeks have passed so I thought I'd give it another go... Your response will be appreciated.

**Comment by 4c0n** [comment]
I'm feeling ignored...

**Comment by LarryKlugerDS** [comment]
Hi @4c0n,

Thank you for your PR!

I have filed internal ticket DCM-3763, asking the engineering team to review your pull request. Unfortunately, the engineering team only has SDK-related sprints periodically, so it will be awhile until they can review your PR. (And we have not missed a sprint since Oct 16th)

We try to keep the OAuth-related methods consistent between the different SDKs, so the team will also be reviewing your PR from that point of view.

**Comment by 4c0n** [comment]
6 months have passed. No action on DocuSign's end whatsoever. Contacting support didn't do anything either. Basically the response is, we don't know if we will ever look at your PR.

It's such a simple and small change, I truly don't understand why it is impossible for someone to schedule 15 to 30 minutes to have a look at this tiny PR and decide if it's good to go or some changes need to be made.

**Comment by LarryKlugerDS** [comment]
Hi @4c0n ,
I have forwarded your very reasonable message to our engineering group. 
Thank you,
Larry

**Comment by 4c0n** [comment]
Thank you Larry.

**Comment by 4c0n** [comment]
@gsnavin The changes have been overwritten in subsequent merges. Could you perhaps merge this again and prevent that from happening?

**Pull request merged**
